import img1 from '../src/imges/270034062_104135072145342_4304221713873365102_n.jpg';
import img2 from '../src/imges/2.jpeg';
import img3 from '../src/imges/t.jpg';
import img4 from '../src/imges/test2.jpg';
import img5 from '../src/imges/ঘি ৫ লিটার.jpg';

export const Users = [
  {
    id: 1,
    profilePicture: img1,
    userName: 'Babar Azam',
  },
  {
    id: 2,
    profilePicture: img2,
    userName: 'Rizwan',
  },
  {
    id: 3,
    profilePicture: img3,
    userName: 'Ramij Raza',
  },
  {
    id: 4,
    profilePicture: img4,
    userName: 'Haris Rauf',
  },
  {
    id: 5,
    profilePicture: img5,
    userName: 'Sakib al Hasan',
  }
];
export const Posts = [
  
  {
    id: 1,
    desc: 'Love for all. Hatared for none',
    photo: img1,
    date: '5 mins ago',
    userId: 1,
    like: 32,
    Comment: '9 Comment',
    share: '10 Share',
    name: 'Saheen Afridi',
  },
  {
    id: 2,
    desc: 'Love for all. Hatred for none',
    photo: img2,
    date: '10 mins ago',
    userId: 2,
    like: 40,
    Comment: '19 Comment',
    share: '7 Share',
    name: 'Shadab Khan',
  },
  {
    id: 3,
    desc: 'Love for all. Hatared for none',
    photo: img3,
    date: '3 mins ago',
    userId: 3,
    like: 20,
    Comment: '10 Comment',
    share: '4 Share',
    name: 'Virat Kohli',
  },
  {
    id: 4,
    desc: 'Love for all. Hatared for none',
    photo: img4,
    date: '55 mins ago',
    userId: 4,
    like: 320,
    Comment: '2 Comment',
    share: '10 Share',
    name: 'Messi',
  },
  {
    id: 5,
    desc: 'Love for all. Hatared for none',
    photo: img5,
    date: '15 mins ago',
    userId: 5,
    like: 22,
    Comment: '5 Comment',
    share: '2 Share',
    name: 'Ronaldo',
  },
  {
    id: 6,
    desc: 'Love for all. Hatared for none',
    photo: img4,
    date: '35 mins ago',
    userId: 4,
    like: 320,
    Comment: '10 Comment',
    share: '10 Share',
    name: 'Sakib al Hasan',
  },
  {
    id: 7,
    desc: 'Love for all. Hatared for none',
    photo: img1,
    date: '25 mins ago',
    userId: 4,
    like: 20,
    Comment: '12 Comment',
    share: '20 Share',
    name: 'Shoaib Malik',
  },
  {
    id: 8,
    desc: 'Love for all. Hatared for none',
    photo: img2,
    date: '55 mins ago',
    userId: 4,
    like: 30,
    Comment: '122 Comment',
    share: '102 Share',
    name: 'Rohit Sharma',
  },
  {
    id: 9,
    desc: 'Love for all. Hatared for none',
    photo: img3,
    date: '55 mins ago',
    userId: 4,
    like: 320,
    Comment: '2 Comment',
    share: '10 Share',
    name: 'Tamim Ikbal',
  },
  {
    id: 9,
    desc: 'Love for all. Hatared for none',
    photo: img5,
    date: '55 mins ago',
    userId: 4,
    like: 320,
    Comment: '2 Comment',
    share: '10 Share',
    name: 'Rashid Khan',
  },
  {
    id: 10,
    desc: 'Love for all. Hatared for none',
    photo: img4,
    date: '55 mins ago',
    userId: 4,
    like: 320,
    Comment: '2 Comment',
    share: '10 Share',
    name: 'Naseem Shah',
  },
];